---
language: node_js
node_js:
- 0.8
before_script:
  - npm install -g grunt-cli
notifications:
  email:
  - 'vincent.pasquier+osf@gmail.com'
  - 'vgrivel+osf@gmail.com'
  - 'geoffrey.papaux+osf@gmail.com'
  - 'doriangambin+osf@gmail.com'